name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
        run: |
          SHA_TAG=git-`echo ${{ github.sha }} | cut -c 1-7`
          BRANCH_TAG=`echo ${{ github.ref }} | sed -e "s!refs/heads/!!g" | sed -e "s!/!-!g" | sed -e "s/^master$/latest/g"`
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHA_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHA_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$SHA_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG
